[profile.default]
src = "src"
test = "test"
libs = ["lib"]
remappings = ["@openzeppelin/contracts/=/opt/solidity/lib/openzeppelin-contracts/contracts/", "forge-std/=/opt/solidity/lib/forge-std/src/"]
ffi = false
fs_permissions = []
auto_detect_remappings = false
auto_detect_solc = true
offline = true
