[profile.default]
src = "src"
test = "test"
libs = ["lib"]
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
ffi = false
fs_permissions = []
auto_detect_remappings = false
auto_detect_solc = true
offline = false
