services:
  default:
    build: .
    image: ethevals-solidity:inputs-68e4835f7eb35167
    init: true
    networks: [private, internet]
  scorer:
    image: ethevals-solidity:inputs-68e4835f7eb35167
    init: true
    networks: [private]
networks:
  private:
    internal: true
  internet: {}
