services:
  default:
    mem_limit: 3g
    build: .
    image: ethevals-solidity:inputs-f7690ccd7debdf27
    init: true
    networks: [private, internet]
  scorer:
    mem_limit: 2g
    image: ethevals-solidity:inputs-f7690ccd7debdf27
    init: true
    networks: [private]
networks:
  private:
    internal: true
    driver_opts:
      com.docker.network.bridge.inhibit_ipv4: "true"
  internet: {}
