services:
  default:
    build: .
    image: ethevals-solidity:inputs-0d3ba8d0e90037d9
    init: true
    networks: [private, internet]
  scorer:
    image: ethevals-solidity:inputs-0d3ba8d0e90037d9
    init: true
    networks: [private, internet]
networks:
  private:
    internal: true
  internet: {}
